const federations = {
    'ЛЬВ' : 'ua-lv',
    'ЧНИ' : 'ua-ch',
    'АРК' : 'ua-kr',
    'ЧНО' : 'ua-cv',
    'ЧРК' : 'ua-ck',
    'ДНЕ' : 'ua-dp',
    'ДОН' : 'ua-dt',
    'ХАР' : 'ua-kk',
    'ХЕР' : 'ua-ks',
    'ХМЕ' : 'ua-km',
    'И-Ф' : 'ua-if',
    'КИР' : 'ua-kh',
    'ЛУГ' : 'ua-lh',
    'НИК' : 'ua-mk',
    'ОДЕ' : 'ua-my',
    'ПОЛ' : 'ua-pl',
    'РОВ' : 'ua-rv',
    'СЕВ' : 'ua-sc',
    'СУМ' : 'ua-sm',
    'ТЕР' : 'ua-tp',
    'ВИН' : 'ua-vi',
    'ВОЛ' : 'ua-vo',
    'ЗАК' : 'ua-zk',
    'ЗАП' : 'ua-zp',
    'КИО' : 'ua-kv',
    'ЖИТ' : 'ua-zt',
    'КИЕ' : 'ua-kc'
}

module.exports = federations;