const urls = [
  'http://ukrchess.org.ua/kvalif/1110/ARK.txt',
  'http://ukrchess.org.ua/kvalif/1110/KIE.txt',
  'http://ukrchess.org.ua/kvalif/1110/SEV.txt',
  'http://ukrchess.org.ua/kvalif/1110/VIN.txt',
  'http://ukrchess.org.ua/kvalif/1110/VOL.txt',
  'http://ukrchess.org.ua/kvalif/1110/DNE.txt',
  'http://ukrchess.org.ua/kvalif/1110/DON.txt',
  'http://ukrchess.org.ua/kvalif/1110/ZIT.txt',
  'http://ukrchess.org.ua/kvalif/1110/ZAK.txt',
  'http://ukrchess.org.ua/kvalif/1110/ZAP.txt',
  'http://ukrchess.org.ua/kvalif/1110/I-F.txt',
  'http://ukrchess.org.ua/kvalif/1110/KIO.txt',
  'http://ukrchess.org.ua/kvalif/1110/KIR.txt',
  'http://ukrchess.org.ua/kvalif/1110/LUG.txt',
  'http://ukrchess.org.ua/kvalif/1110/LUG.txt',
  'http://ukrchess.org.ua/kvalif/1110/LVO.txt',
  'http://ukrchess.org.ua/kvalif/1110/NIK.txt',
  'http://ukrchess.org.ua/kvalif/1110/ODE.txt',
  'http://ukrchess.org.ua/kvalif/1110/POL.txt',
  'http://ukrchess.org.ua/kvalif/1110/ROV.txt',
  'http://ukrchess.org.ua/kvalif/1110/SUM.txt',
  'http://ukrchess.org.ua/kvalif/1110/TER.txt',
  'http://ukrchess.org.ua/kvalif/1110/HAR.txt',
  'http://ukrchess.org.ua/kvalif/1110/HER.txt',
  'http://ukrchess.org.ua/kvalif/1110/HME.txt',
  'http://ukrchess.org.ua/kvalif/1110/CRK.txt',
  'http://ukrchess.org.ua/kvalif/1110/CNI.txt',
  'http://ukrchess.org.ua/kvalif/1110/CNO.txt',
];

module.exports = urls;
